name: Run Custdocian

on:
  push:
    branches:
      - main

env:
  SCRIPT_PATH: .github/bin

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Custdocian
        run: python ${SCRIPT_PATH}/custdocian.py

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "."
          message: "docs(custdocian): Updated README.md"
